use havik
go
select nome  from bh_cli_consultor_obs obs 


full outer join bc_cliente base
on obs.id_cliente = base.id


where nome in (

'Helio Murai',
'Diego Rodrigues Fernandes',
'Thiago de Andrade Nakano',
'Danilo Augusto Moreira',
'Rodrigo Fittipaldi',
'Mario Henrique amarante',
'Deborah Furuko Matsumoto',
'Maurício Brandao Teodoro',
'Daniel Rosenfeld',
'Aramis Araujo',
'Wallace Martins',
'Daniel Bento',
'Clauber de Oliveira Miranda',
'Vitor Pratta Ferrata', 
'Fabiana Castello',
'Rafael Lopes rocha',
'Leandro Gomes', 
'Marcus Vinicius Veiga Tavora',
'Rodrigo Prado Monteiro', 
'Diego Pinheiro Fernandes Junior',
'Marco Aurelio Ferreira',
'Leonardo Quesada',
'Rafael Hisashi Hirose',
'Guilherme Augusto Alves Pereira',
'Nayara Lany de Padua', 
'Joao Paulo Machado Corrêa',
'Hagner Leao Costa Ribeiro', 
'Fabio da Silva Tieghi',
'Douglas Campos de Oliveira',
'Paulo Benedetti',
'Renan Henrique de Melo Affonso',
'Tales Marland',
'Leandro Andrade Trovao',
'Welton Teixeira de Moraes Lima',
'Debora Ugarte',
'Alexandre Rodrigues Xavier',
'Rodrigo Cunha Gaspar',
'Daniela Andrade',
'Adriel Tangioni de Andrade',
'Fabiano Affonso dos Santos',
'Alexandra Brumatti',
'Amanda Amaral Silva',
'Leonardo Alex Ogura',
'Daniel Rosenfeld',
'Tatiana Scarpioni',
'Juliano Ribeiro',
'Thiago Valente',
'ERIK HENRIQUE MATIOLI',
'Jose Fernandes Junior',
'Arthur Bergamini Drummond',
'Andre Fontana',
'Rafael Gonçalo Mendes Soares Montilha',
'Danilo Camargo',
'Renato Aparecido Souza da Silva',
'Valquiria Cordeiro Cavalcanti',
'Erika Quadros Domingues',
'Priscila Gonçalves de Queiroz',
'Adriano de Oliveira Rizzo',
'Bruno Rizzato Coelho Pina',
'Adriano Sedemac',
'Rodolfo Peroto Siqueira',
'Andre Costa Mariotti', 
'Renato Marcovitti Pedro',
'Lauro Americo dos Santos',
'Joglas Do Nascimento Souza',
'Marcelo Hideki Akimura',
'Raphael Francisco Gritti Ferreira',
'Airton de Melo',
'Aline Mazzoni Zaccarelli',
'Diego Riciardi',
'Rafael Fercondini',
'Conrado Grinberg Garci',
'Wellington Balthazar Baldocchi Parra Viudes',
'Lucas Safont Pereira',
'Robson Roberto de Oliveira',
'Bruno Wilson da Conceicao',
'Olivia Xavier Santos Carvalho',
'Douglas Marra da Costa',
'Denis Storti',
'Rafael Ching Lau',
'Lizarb Placido Dias',
'Julio da Silva Filho',
'Leandro Netto Trindade',
'Erika Batista Facundo Conti',
'Ronaldo Souza Barbosa',
'Silvia Nunes',
'Fabio Caccavale',
'Patricia Kowalski Duraes',
'Samantha Malvezzi',
'Marilia Scotini',
'Cristiane de Paula',
'Vanieli Eloy Anduia',
'Luana Alves Barbosa',
'Maycon Tome',
'Juliana dos Santos Rodrigues',
'Rafael Ching Lau',
'Julio da Silva Filho',
'Guilherme Holdack',
'Rubens Cury Filho'
)
group by nome
having count(obs.id_cliente) > 0 --or count(obs.id_cliente) = 0

--order by base.id