create table rh.dim_tempo
(
cod_tempo int primary key not null,
data date,
ano_mes_dia char(10),
ano int,
mes int,
dia int,
ano_mes char(7),
ano_mes_nome varchar(15),
ano_mes_nome_abrev char(8),
anomes int,
mes_nome varchar(9),
mes_nome_abrev varchar(3),
dia_da_semana int,
dia_da_semana_nome varchar(7),
dia_do_ano int,
bimestre int,
trimestre int,
semestre int,
semana_mes int,
semana_ano int,
ano_bimestre char(7),
ano_trimestre char(7),
ano_semestre char(7),
dia_util int,
final_semana int,
data_por_extenso varchar(50)
)