use havik_teste
go
insert into br_equipe
(
id_lider,
id_colaborador,
funcao,
cargo,
home,
usuario_alteracao,
dt_alteracao
)
values
(3,52,'Associado','Consultor Associado','Consultor',1,getdate()),
(3,82,'Associado','Consultor Associado','Consultor',1,getdate()),
(3,91,'Associado','Consultor Associado','Consultor',1,getdate()),
(3,22,'Consultor','Consultor','Consultor',1,getdate()),
(3,88,'Research','Research','R1',1,getdate()),
(3,90,'Assistente','Assistente','R1',1,getdate()),
(3,73,'Assistente','Assistente','R1',1,getdate()),
(3,78,'Assistente','Assistente','R1',1,getdate()),
(3,70,'Assistente','Assistente','R1',1,getdate()),
(3,55,'Assistente','Assistente','R1',1,getdate()),
(3,81,'Assistente','Assistente','R1',1,getdate()),
(3,74,'Estagiário','Estagiário','R1',1,getdate()),
(3,96,'Estagiário','Estagiário','R1',1,getdate()),
(3,1,'Estagiário','Estagiário','R1',1,getdate()),
(21,95,'Associado','Consultor Associado','Consultor',1,getdate()),
(21,54,'Associado','Consultor Associado','Consultor',1,getdate()),
(21,25,'Associado','Consultor Associado','Consultor',1,getdate()),
(11,85,'Associado','Consultor Associado','Consultor',1,getdate()),
(11,76,'Research','Research','R1',1,getdate()),
(15,93,'Associado','Consultor Associado','Consultor',1,getdate()),
(15,8,'Consultor','Consultor','Consultor',1,getdate()),
(15,38,'Consultor','Consultor','Consultor',1,getdate()),
(15,23,'Research','Research','R1',1,getdate()),
(36,94,'Associado','Consultor Associado','Consultor',1,getdate()),
(36,86,'Associado','Consultor Associado','Consultor',1,getdate()),
(36,33,'Consultor','Consultor','Consultor',1,getdate()),
(36,34,'Consultor','Consultor','Consultor',1,getdate()),
(36,72,'Research','Research','R1',1,getdate()),
(36,79,'Estagiário','Estagiário','R1',1,getdate()),
(36,83,'Estagiário','Estagiário','R1',1,getdate()),
(36,92,'Estagiário','Estagiário','R1',1,getdate()),
(36,80,'Estagiário','Estagiário','R1',1,getdate()),
(47,89,'Associado','Consultor Associado','Consultor',1,getdate()),
(26,87,'Associado','Consultor Associado','Consultor',1,getdate()),
(26,69,'Research','Research','R1',1,getdate()),
(6,67,'Assistente','Assistente','Assistente',1,getdate()),
(3,3,'Partner','Partner','Partner',1,getdate()),
(6,6,'Partner','Partner','Partner',1,getdate()),
(26,26,'Partner','Partner','Partner',1,getdate()),
(36,36,'Partner','Partner','Partner',1,getdate()),
(15,15,'Partner','Partner','Partner',1,getdate()),
(21,21,'Partner','Partner','Partner',1,getdate()),
(11,11,'Partner','Partner','Partner',1,getdate()),
(47,47,'Partner','Partner','Partner',1,getdate()),
(57,57,'Coodenador','Coordenador','Coordenador',1,getdate()),
(60,60,'Consultor','Consultor Externo','Coordenador',1,getdate())

